config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  
  resources :days_of_the_weeks
  resources :todo_list_items
  resources :todos
  resources :dailies 
  resources :profiles
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/todo_list_item.rb
class TodoListItem < ApplicationRecord
    belongs_to :todo    
end

app/controllers/todo_list_items_controller.rb
class TodoListItemsController < ApplicationController
  before_action :set_todo_list_item, only: [:show, :edit, :update, :destroy]

  # GET /todo_list_items
  # GET /todo_list_items.json
  def index
    @todo_list_items = TodoListItem.all
  end

  # GET /todo_list_items/1
  # GET /todo_list_items/1.json
  def show
  end

  # GET /todo_list_items/new
  def new
    @todo_list_item = TodoListItem.new
  end

  # GET /todo_list_items/1/edit
  def edit
  end

  # POST /todo_list_items
  # POST /todo_list_items.json
  def create
    @todo_list_item = TodoListItem.new(todo_list_item_params)

    respond_to do |format|
      if @todo_list_item.save
        format.html { redirect_to admin_url, notice: 'List item was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list_item }
      else
        format.html { render :new }
        format.json { render json: @todo_list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_list_items/1
  # PATCH/PUT /todo_list_items/1.json
  def update
    respond_to do |format|
      if @todo_list_item.update(todo_list_item_params)
        format.html { redirect_to admin_url, notice: 'List item was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list_item }
      else
        format.html { render :edit }
        format.json { render json: @todo_list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_list_items/1
  # DELETE /todo_list_items/1.json
  def destroy
    @todo_list_item.destroy
    respond_to do |format|
      format.html { redirect_to todo_list_items_url, notice: 'Todo List item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list_item
      @todo_list_item = TodoListItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_item_params
      params.require(:todo_list_item).permit( :todo_id, :complete, :task, :counter, :difficultyLvl, :experiencePoints)
    end
end

app/views/todo_list_items/_form.html.erb
<%= form_with(model: todo_list_item, local: true) do |form| %>
  <% if todo_list_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_list_item.errors.count, "error") %> prohibited this todo_list_item from being saved:</h2>

      <ul>
      <% todo_list_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :complete %>
    <%= form.check_box :complete %>
  </div>

  <div class="field">
    <%= form.label :task %>
    <%= form.text_field :task %>
  </div>

  <div class="field">
    <%= form.label :counter %>
    <%= form.number_field :counter %>
  </div>

  <div class="field">
    <%= form.label :difficultyLvl %>
    <%= form.number_field :difficultyLvl %>
  </div>

  <div class="field">
    <%= form.label :experiencePoints %>
    <%= form.number_field :experiencePoints %>
  </div>


  

       <%= form.hidden_field :todo_id, :value => params[:todo_id] %>
 

  <div class="actions">
    <%= form.submit %>
  </div>

<%= debug(params) %>

<% end %>

app/views/todo_list_items/edit.html.erb
<h1>Editing Todo List Item</h1>

<%= render 'form', todo_list_item: @todo_list_item %>

<%= link_to 'Show', @todo_list_item %> |
<%= link_to 'Back', todo_list_items_path %>

app/views/todo_list_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List Items</h1>

<table>
  <thead>
    <tr>
      <th>Complete</th>
      <th>Task</th>
      <th>Counter</th>
      <th>Difficulty Level</th>
      <th>Experience Points</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_list_items.each do |todo_list_item| %>
      <tr>
        <td><%= todo_list_item.complete %></td>
        <td><%= todo_list_item.task %></td>
        <td><%= todo_list_item.counter %></td>
        <td><%= todo_list_item.difficultyLvl %></td>
        <td><%= todo_list_item.experiencePoints %></td>
        <td><%= link_to 'Show', todo_list_item %></td>
        <td><%= link_to 'Edit', edit_todo_list_item_path(todo_list_item) %></td>
        <td><%= link_to 'Destroy', todo_list_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo List Item', new_todo_list_item_path %>

app/views/todo_list_items/new.html.erb
<h1>New List Item</h1>

<%= render 'form', todo_list_item: @todo_list_item %>

<%= link_to 'Back', todo_list_items_path %>

app/views/todo_list_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Complete:</strong>
  <%= @todo_list_item.complete %>
</p>

<p>
  <strong>Task:</strong>
  <%= @todo_list_item.task %>
</p>

<p>
  <strong>Counter:</strong>
  <%= @todo_list_item.counter %>
</p>

<p>
  <strong>Difficulty Level:</strong>
  <%= @todo_list_item.difficultyLvl %>
</p>

<p>
  <strong>Experience Points:</strong>
  <%= @todo_list_item.experiencePoints %>
</p>

<%= link_to 'Edit', edit_todo_list_item_path(@todo_list_item) %> |
<%= link_to 'Back', todo_list_items_path %>