config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  
  resources :days_of_the_weeks
  resources :todo_list_items
  resources :todos
  resources :dailies 
  resources :profiles
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/daily.rb
class Daily < ApplicationRecord
    belongs_to :user
    has_many :listItems
end

app/controllers/dailies_controller.rb
class DailiesController < ApplicationController
  before_action :set_daily, only: [:show, :edit, :update, :destroy]

  # GET /dailies
  # GET /dailies.json
  def index
    @dailies = Daily.all
  end

  # GET /dailies/1
  # GET /dailies/1.json
  def show
  end

  # GET /dailies/new
  def new
    @daily = Daily.new
  end

  # GET /dailies/1/edit
  def edit
  end

  # POST /dailies
  # POST /dailies.json
  def create
    @daily = Daily.new(daily_params)

    respond_to do |format|
      if @daily.save
        format.html { redirect_to @daily, notice: 'Daily was successfully created.' }
        format.json { render :show, status: :created, location: @daily }
      else
        format.html { render :new }
        format.json { render json: @daily.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dailies/1
  # PATCH/PUT /dailies/1.json
  def update
    respond_to do |format|
      if @daily.update(daily_params)
        format.html { redirect_to @daily, notice: 'Daily was successfully updated.' }
        format.json { render :show, status: :ok, location: @daily }
      else
        format.html { render :edit }
        format.json { render json: @daily.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dailies/1
  # DELETE /dailies/1.json
  def destroy
    @daily.destroy
    respond_to do |format|
      format.html { redirect_to dailies_url, notice: 'Daily was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_daily
      @daily = Daily.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def daily_params
      params.require(:daily).permit(:streak, :user_id)
    end
end

app/helpers/dailies_helper.rb
module DailiesHelper
end

app/views/dailies/_form.html.erb
<%= form_with(model: daily, local: true) do |form| %>
  <% if daily.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(daily.errors.count, "error") %> prohibited this daily from being saved:</h2>

      <ul>
      <% daily.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :streak %>
    <%= form.number_field :streak %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dailies/edit.html.erb
<h1>Editing Daily</h1>

<%= render 'form', daily: @daily %>

<%= link_to 'Show', @daily %> |
<%= link_to 'Back', dailies_path %>

app/views/dailies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dailies</h1>

<table>
  <thead>
    <tr>
      <th>Streak</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dailies.each do |daily| %>
      <tr>
        <td><%= daily.streak %></td>
        <td><%= link_to 'Show', daily %></td>
        <td><%= link_to 'Edit', edit_daily_path(daily) %></td>
        <td><%= link_to 'Destroy', daily, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Daily', new_daily_path %>

app/views/dailies/new.html.erb
<h1>New Daily</h1>

<%= render 'form', daily: @daily %>

<%= link_to 'Back', dailies_path %>

app/views/dailies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Streak:</strong>
  <%= @daily.streak %>
</p>

<%= link_to 'Edit', edit_daily_path(@daily) %> |
<%= link_to 'Back', dailies_path %>